<?xml version="1.0"?>
<package format="3">
  <name>rav_manipulation_sim</name>
  <version>0.0.1</version>
  <description>Mock vision to MoveIt pipeline for the RAV manipulator in Gazebo.</description>
  <maintainer email="nathan@example.com">Nathan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>

  <exec_depend>rav_physics_sim</exec_depend>
  <exec_depend>rav_manipulator_moveit_config</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
